language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.9
    - RACKET_VERSION=RELEASE

matrix:
  allow_failures:
    - env: RACKET_VERSION=RELEASE

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
  - raco pkg install --no-setup rosette graph
  - raco setup -Dl rosette graph

install:
  - raco pkg install

# Here supply steps such as raco make, raco test, etc.
script:
  - racket src/test/all-test.rkt
